name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  
  build-and-test:
    runs-on: ubuntu-latest
    services:
        cosmosdb:
            image: mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator
            ports:
                - 8081:8081
                - 8900:8900
                - 8901:8901
                - 8902:8902
                - 10250:10250
                - 10251:10251
                - 10252:10252
                - 10253:10253
                - 10254:10254
                - 10255:10255
                - 10256:10256
                - 10350:10350
            env:
                - AZURE_COSMOS_EMULATOR_PARTITION_COUNT=2
                - AZURE_COSMOS_EMULATOR_ENABLE_DATA_PERSISTENCE=true
                - AZURE_COSMOS_EMULATOR_IP_ADDRESS_OVERRIDE=127.0.0.1    
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x
        
        # run build and test           
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Test
        run: dotnet test --no-build --verbosity normal /p:CollectCoverage=true /p:CoverletOutputFormat=lcov /p:CoverletOutput=ManagedCode.Repository.Tests/lcov.info
      - name: docker run fake-gcs-server
        run: |
            docker run -d --name fake-gcs-server -p 8081:8081 -v ${PWD}/examples/data:/data fsouza/fake-gcs-server -scheme http -external-url "http://localhost:8081"
            sleep 5s

      #- name: coverlet
      #  uses: b3b00/coverlet-action@1.1.9
      #  with:
      #    testProject: 'ManagedCode.Database.Tests/ManagedCode.Database.Tests.csproj'
      #    output: 'lcov.info'
      #    outputFormat: 'lcov'
      #    excludes: '[program]*,[test]test.*'
      #- name: coveralls
      #  uses: coverallsapp/github-action@master
      #  with:
      #    github-token: ${{secrets.GITHUB_TOKEN }}
      #    path-to-lcov: ManagedCode.Storage.Tests/lcov.info
